add gradle for jLib using SettingsLib
includes the following from 16-QPR2

use google findbugs for javax

AGP 9

restrict spinner width in spinnerpref2

Add Kotlin source files to SettingsSpinner

migrate to onBackPressedCallback

fix URLs on maven

add CardPreference to gradle

fix for agp 9.2

fix deprecation warning

publish settingslib gradle dep again

stop configuring maven publishing variant

Revert "stop configuring maven publishing variant"

javadocs are broken for sealed classes, see
https://github.com/Kotlin/dokka/issues/2956 for more info about the bug

This reverts commit 70595a70604a9c0e2769c0cd8d4fe64de208939e.

make gradle SettingsLib independent

add MenuPreference

add CI

fixes

improve description of new versioning

fixes

update deps

begin building SPA

bundle all deps in SettingsLib

fix issue

fixes pkg:maven/io.github.dot166/SettingsLibSpa@136.1.202606042126
Error: Dependency version information is missing for dependency: androidx.lifecycle:lifecycle-runtime-compose

drop unused legacy pref modules

fix SpaLib name

try to fix AOSP jLib

create SpinnerPreference

add default values to SpinnerPreferenceModel

Update libs.versions.toml

fix com.android.settings